Encryption now expects terms to be pre-encoded
cipherstash/node-ore-rs pull request #8
Opened 2022-01-31 01:43 UTC by freshtonic

- add dependency on ore_encoding.rs
- only accept JSNumber as arg to encrypt function
- assume arg is pre-encoded
- update tests to encode terms before encryption
- export ORE.encode(JsNumber) function

2022-01-31 03:03 UTC, coderdan commented
It looks like you've removed the functions to encrypt BigNum and Buffer values which means we rely only on JsNumber for all input types to the ORE encrypt functions. This means that the max value we can encrypt is `2^53-1` which will not work for Siphash encoded terms (64-bit output) as this could result in collisions.

2022-01-31 03:03 UTC, coderdan requested changes

2022-01-31 04:15 UTC, freshtonic commented on native/lib.rs
> +    let input: u64 = cx.argument::<JsNumber>(1)?.value(&mut cx).to_bits();
@coderdan `to_bits` is a Clippy-suggested safe version of `std::mem::transmute` - it would appear to be "idiomatic Rust (according to Clippy anyway).

2022-01-31 04:26 UTC, freshtonic commented
> It looks like you've removed the functions to encrypt BigNum and Buffer values which means we rely only on JsNumber for all input types to the ORE encrypt functions. This means that the max value we can encrypt is `2^53-1` which will not work for Siphash encoded terms (64-bit output) as this could result in collisions.

We won't lose precision with a JsNumber - it's just 8 bytes - we never treat it as a JS number as it's always transmuted into a u64 before we do anything interesting with it.

What I think we should do though is provide `encodeBigInt` and `encodeBuffer` native functions that return a JsNumber (f64).

Does that make sense?

2022-01-31 05:13 UTC, coderdan commented
I don't understand why we are doing everything in JsNumber when Buffer is available. Is it a performance consideration?

2022-01-31 05:17 UTC, coderdan commented on native/lib.rs
> +    let input: u64 = cx.argument::<JsNumber>(1)?.value(&mut cx).to_bits();
Oh right ok!

2022-01-31 05:20 UTC, coderdan commented
@freshtonic `Number` is JavaScript will be a much less common case than for text. Even if we have one text field and one number field, the text field will likely result in mulitple terms vs only one for the number field (during insertion anyway). The SipHash code in the equality encoder generates a Buffer so using the approach in this PR we'd have to call SipHash, convert the resulting Buffer to a Number and then encrypt that. Where as if we just allow the functions in this lib to take Buffer we save ourselves a step.

Side note: Encrypting equality should be a dedicated scheme in the ore.rs lib which would make this somewhat redundant anyway.

2022-02-01 01:16 UTC, freshtonic commented on native/lib.rs
> -fn encrypt_buf(mut cx: FunctionContext) -> JsResult<JsBuffer> {
Only for siphash results (which now happens in Rust - yay!)

2022-02-01 01:24 UTC, coderdan approved these changes
Nice work!

2022-02-01 03:30 UTC, merged