Pass plaintexts around as buffers
cipherstash/node-ore-rs pull request #9
Opened 2022-02-25 13:04 UTC by mpalmer

This prevents any possible unpleasantnesses caused by passing numbers around
inside the JavaScript interpreter.  Also tightened up some of the types
exported, so that it's a (bit) harder to accidentally make ranges out of an
unencoded value, or double-encode a value.

2022-02-27 08:31 UTC, coderdan commented on native/lib.rs
> +        let slice8: [u8; 8] = [slice[0], slice[1], slice[2], slice[3], slice[4], slice[5], slice[6], slice[7]];
Does `let slice8: [u8; 8] = slice[0..8]` work?

2022-02-27 08:40 UTC, coderdan requested changes
Generally, I think this looks OK though I would just ask that you remove the panics.

It's a shame that we have to call out to rust twice but cest la vie. It will all be rust soon enough.

2022-02-27 23:23 UTC, mpalmer commented on native/lib.rs
> +        let slice8: [u8; 8] = [slice[0], slice[1], slice[2], slice[3], slice[4], slice[5], slice[6], slice[7]];
Dunno, I'll give it a go.  I just cargo-culted that from [existing code](https://github.com/cipherstash/node-ore-rs/blob/main/native/lib.rs#L121).

2022-02-27 23:32 UTC, mpalmer commented on native/lib.rs
> +        let slice8: [u8; 8] = [slice[0], slice[1], slice[2], slice[3], slice[4], slice[5], slice[6], slice[7]];
Hmm, nope, that doesn't seem to work:

```
error[E0308]: mismatched types
   --> native/lib.rs:123:31
    |
123 |         let slice8: [u8; 8] = slice[0..8];
    |                     -------   ^^^^^^^^^^^ expected array `[u8; 8]`, found slice `[u8]`
    |                     |
    |                     expected due to this
```

On the other hand, I'm thinking that a loop might be a better solution anyway, so I'll switch to that.  It'll at least be less ugly.

2022-02-27 23:40 UTC, mpalmer commented on native/lib.rs
> +        let slice8: [u8; 8] = [slice[0], slice[1], slice[2], slice[3], slice[4], slice[5], slice[6], slice[7]];
Hmm, nope, you still need to init the slice before you loop over it (even when you're just assigning to it), so that's no real benefit.

2022-02-28 02:07 UTC, coderdan commented on native/lib.rs
> +    let input: u64 = match u64_from_buffer(&cx, arg) {
Nothing wrong with this but you could use `or_else` to make it a bit more concise. The `Ok` case is kinda redundant.

2022-02-28 02:08 UTC, coderdan approved these changes
A small style suggestion but otherwise LGTM

2022-02-28 02:19 UTC, merged